
CREATE TABLE COMPANY
(
  ID      VARCHAR(200) NOT NULL COMMENT 'ui',
  NAME    VARCHAR(200) NOT NULL COMMENT '이름',
  AGE     INT          NULL     COMMENT '나이',
  ADDRESS VARCHAR(200) NULL     COMMENT '주소',
  SALARY  INT          NOT NULL COMMENT '봉급',
  PRIMARY KEY (ID)
) COMMENT '회사';

CREATE TABLE COMPANY_DPT
(
  COMPANY_ID VARCHAR(200) NOT NULL COMMENT 'ui',
  DEPT_ID    VARCHAR(200) NOT NULL COMMENT 'ui'
) COMMENT '관계 테이블';

CREATE TABLE DEPARTMENT
(
  ID   VARCHAR(200) NOT NULL COMMENT 'ui',
  DEPT VARCHAR(200) NOT NULL COMMENT '부서',
  PRIMARY KEY (ID)
) COMMENT '부서';

ALTER TABLE COMPANY_DPT
  ADD CONSTRAINT FK_COMPANY_TO_COMPANY_DPT
    FOREIGN KEY (COMPANY_ID)
    REFERENCES COMPANY (ID);

ALTER TABLE COMPANY_DPT
  ADD CONSTRAINT FK_DEPARTMENT_TO_COMPANY_DPT
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT (ID);
